<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <DefaultItemExcludes>$(DefaultItemExcludes);FixViewsApp\**;AgvDispatcher.Shell\**;AgvDispatcher.Core\**;AgvDispatcher.Modules.TemplateModule\**;AgvDispatcher.Modules.DashboardModule\**;AgvDispatcher.Modules.MonitoringModule\**;AgvDispatcher.Modules.MapModule\**;AgvDispatcher.Modules.MonitorWorkspaceModule\**;AgvDispatcher.Modules.ChargeModule\**;AgvDispatcher.Modules.TaskModule\**;AgvDispatcher.Modules.SignalModule\**;AgvDispatcher.Modules.DataQueryModule\**;AgvDispatcher.Modules.TaskConfigModule\**</DefaultItemExcludes>
  </PropertyGroup>

</Project>
