<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <DefaultItemExcludes>$(DefaultItemExcludes);*.cs;FixViewsApp\**;TestDbRunner\**;okapi\**;agv-physics-video\**;AgvDispatcher.Shell\**;AgvDispatcher.DebugDashboard\**;AgvDispatcher.Tests\**;AgvDispatcher.Core\**;AgvDispatcher.Application\**;AgvDispatcher.Infrastructure.Mock\**;AgvDispatcher.Infrastructure.Okapi\**;AgvDispatcher.Infrastructure.Sqlite\**;AgvDispatcher.Modules.TemplateModule\**;AgvDispatcher.Modules.DashboardModule\**;AgvDispatcher.Modules.MonitoringModule\**;AgvDispatcher.Modules.MapModule\**;AgvDispatcher.Modules.MonitorWorkspaceModule\**;AgvDispatcher.Modules.ChargeModule\**;AgvDispatcher.Modules.TaskModule\**;AgvDispatcher.Modules.SignalModule\**;AgvDispatcher.Modules.DataQueryModule\**;AgvDispatcher.Modules.TaskConfigModule\**;AgvDispatcher.Modules.SystemConfigModule\**</DefaultItemExcludes>
  </PropertyGroup>

</Project>
